file = open('test.json','r')
ttt = file.readlines()
print(ttt[-2])
file2 = open('test.json','r+')
tttw = file2.readlines()
print(tttw[-2])
file2.write('111')
# file.writelines(-2,'ttt')
# print(file.)
